/**
 * Maps old icon names to Material Icons names
 * Reference: https://fonts.google.com/icons
 */
export const iconMapping = {
  // Navigation & UI
  FiHome: 'home',
  FiLayers: 'layers',
  FiImage: 'image',
  FiLogOut: 'logout',
  FiChevronLeft: 'chevron_left',
  FiChevronRight: 'chevron_right',
  FiZap: 'bolt',
  FiVideo: 'videocam',
  FiFolder: 'folder',
  FiBell: 'notifications',
  FiSettings: 'settings',
  FiUser: 'person',
  FiMail: 'mail',
  FiSearch: 'search',
  FiPlus: 'add',
  FiMinus: 'remove',
  FiX: 'close',
  FiCheck: 'check',
  FiEdit: 'edit',
  FiTrash: 'delete',
  FiDownload: 'download',
  FiUpload: 'upload',
  FiShare: 'share',
  FiStar: 'star',
  FiHeart: 'favorite',
  FiLock: 'lock',
  FiUnlock: 'lock_open',
  FiInfo: 'info',
  FiAlertCircle: 'error',
  FiCheckCircle: 'check_circle',
  FiCalendar: 'calendar_today',
  FiClock: 'schedule',
  FiMenu: 'menu',
  FiMoreVertical: 'more_vert',
  FiMoreHorizontal: 'more_horiz',
  FiArrowLeft: 'arrow_back',
  FiArrowRight: 'arrow_forward',
  FiArrowUp: 'arrow_upward',
  FiArrowDown: 'arrow_downward',
  FiExternalLink: 'open_in_new',
  FiLink: 'link',
  FiCopy: 'content_copy',
  FiFilter: 'filter_list',
  FiGrid: 'grid_view',
  FiList: 'list',
  FiRefresh: 'refresh',
  FiSave: 'save',
  FiPrinter: 'print',
  FiCamera: 'camera',
  FiMonitor: 'desktop_windows',
  FiSmartphone: 'smartphone',
  FiTablet: 'tablet',
  FiGlobe: 'language',
  FiCloudUpload: 'cloud_upload',
  FiCloudDownload: 'cloud_download',
  
  // Social & Communication
  FiFacebook: 'facebook',
  FiTwitter: 'twitter',
  FiInstagram: 'photo_camera',
  FiLinkedin: 'work',
  FiYoutube: 'play_circle',
  FiPhone: 'phone',
  FiMessageCircle: 'chat',
  FiMail: 'mail',
  
  // File & Document
  FiFile: 'description',
  FiFileText: 'article',
  FiImage: 'image',
  FiVideo: 'videocam',
  FiMusic: 'music_note',
  FiZip: 'folder_zip',
  FiPdf: 'picture_as_pdf',
  
  // E-commerce & Shopping
  FiShoppingCart: 'shopping_cart',
  FiCreditCard: 'credit_card',
  FiTag: 'local_offer',
  FiPackage: 'inventory',
  FiTruck: 'local_shipping',
  FiDollarSign: 'attach_money',
  
  // Weather & Nature
  FiSun: 'light_mode',
  FiMoon: 'dark_mode',
  FiCloud: 'cloud',
  FiWind: 'air',
  FiUmbrella: 'umbrella',
  
  // Others
  FiActivity: 'trending_up',
  FiAirplay: 'cast',
  FiAward: 'military_tech',
  FiBook: 'book',
  FiBookmark: 'bookmark',
  FiClipboard: 'content_paste',
  FiCompass: 'explore',
  FiDatabase: 'storage',
  FiFlag: 'flag',
  FiGift: 'redeem',
  FiGitBranch: 'fork_right',
  FiHash: 'tag',
  FiHeadphones: 'headphones',
  FiLifeBuoy: 'support',
  FiMap: 'map',
  FiMapPin: 'location_on',
  FiPaperclip: 'attach_file',
  FiPieChart: 'pie_chart',
  FiPower: 'power_settings_new',
  FiSliders: 'tune',
  FiTool: 'build',
  FiTrendingUp: 'trending_up',
  FiTrendingDown: 'trending_down',
  FiWifi: 'wifi',
  FiZoomIn: 'zoom_in',
  FiZoomOut: 'zoom_out'
};
